CAMERA_TYPE = "MOCK"
DRIVE_TRAIN_TYPE = "MOCK"
CONTROLLER_TYPE = "MOCK"  # (MOCK|BACKEND)

STEERING_CHANNEL = 1
STEERING_LEFT_PWM = 460
STEERING_RIGHT_PWM = 290
THROTTLE_CHANNEL = 0
THROTTLE_FORWARD_PWM = 500
THROTTLE_STOPPED_PWM = 370
THROTTLE_REVERSE_PWM = 220
