CAMERA_TYPE = "PICAM"  # (MOCK|PICAM)
DRIVE_TRAIN_TYPE = "PWM_STEERING_THROTTLE" #(MOCK|PWM_STEERING_THROTTLE)

USER_CONTROLLER = True
CONTROLLER_TYPE = "MOCK"  # (MOCK|BACKEND)

DONKEY_GYM = True
DONKEY_SIM_PATH = "D:\projects\DonkeySimWin\donkey_sim.exe"
DONKEY_GYM_ENV_NAME = "donkey-generated-track-v0"
