CAMERA_TYPE = "PICAM"  # (MOCK|PICAM)
DRIVE_TRAIN_TYPE = "PWM_STEERING_THROTTLE" #(MOCK|PWM_STEERING_THROTTLE)
CONTROLLER_TYPE = "MOCK"  # (MOCK|BACKEND)

# STEERING_CHANNEL = 1
# STEERING_LEFT_PWM = 480
# STEERING_RIGHT_PWM = 310
# THROTTLE_CHANNEL = 0
# THROTTLE_FORWARD_PWM = 500
# THROTTLE_STOPPED_PWM = 370
# THROTTLE_REVERSE_PWM = 220

DONKEY_GYM = False
DONKEY_SIM_PATH = "D:\projects\DonkeySimWin\donkey_sim.exe"
DONKEY_GYM_ENV_NAME = "donkey-generated-track-v0"
